parameters:

services:
  _defaults:
    public:        true



##### Austral Event Subscriber
  austral.cache.event_subscriber:
    class:        Austral\CacheBundle\EventSubscriber\HttpCacheSubscriber
    arguments:
      - "@austral.cache.http_cache"
      - "@austral.cache.config"
    tags:
      - { name: kernel.event_subscriber }

##### Http Listener Kernel

  austral.cache.listener:
    class: Austral\CacheBundle\Listener\CacheListener
    arguments:
      - "@austral.cache.config"
      - "@austral.tools.debug"
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onResponse, priority: -2096 }

##### Cache Services

  austral.cache.http_cache:
    class:          Austral\CacheBundle\Services\HttpCache
    arguments:      ["@kernel", "@http_cache.store", "@?esi"]

  http_cache:
    class:          Austral\CacheBundle\Services\HttpCache
    arguments:      ["@kernel", "@http_cache.store", "@?esi"]

##### Configuration

  austral.cache.config:
    class:      Austral\CacheBundle\Configuration\CacheConfiguration
    arguments:  [ "%austral_cache%" ]