austral_cache:
  enabled:            false
  clearAuto:          false
  shared_age_max:     3600
  include:
    path:             []
    domain:           []
  exclude:
    path:             []
    domain:           []

